#!/usr/bin/env bash
# configuring a nginx server to have a custom 404 page
# the page must return an HTTP 404 error code

apt-get update
apt-get upgrade
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
touch /etc/nginx/html/404.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html

print %s "server {
    listen  80 default_server;
    listen  [::]:80 default_server;
    root    /etc/nginx/html;
    index   index.html
    }

    error_page 404 /404.html;
    location /404 {
        root /etc/nginx/html;
        internal;

}" > /etc/nginx/sites-available/default

service nginx restart
