#!/usr/bin/env bash
# A Bash script that displays the time for 12 hours and 59 minutes:
#    display hours from 0 to 12
#    display minutes from 1 to 59
hour=1
while [ $hour -le 12 ]
do
    echo "Hour: $hour"
    minute=1
    while [ $minute -le 59 ]
    do
        printf "%d\n" $minute
        ((minute++))
    done
    hour=$((hour+1))
done
